services:
  ollama:
    image: ollama/ollama
    container_name: MailBurner_Ollama
    ports:
      - 11434:11434
    volumes:
      - ollama-data:/root/.ollama

  redis:
    image: redis/redis-stack
    container_name: MailBurner_Redis
    ports:
      - 6379:6379

volumes:
  ollama-data: